plugins:
    mist:
        executor: central_deployment_agent
        source:https://github.com/mistio/cloudify-mist-plugin/archive/testing.zip

node_types:
  cloudify.mist.nodes.Server:
    derived_from: cloudify.nodes.Compute
    properties:
      username:
        default: ''
      password:
        default: ''
      backend_id:
        default: ''
      image_id:
        default: ''
      size_id: 
        default: ''
      location_id:
        default: ''
      name:
        default: ''
      key:
        default: ''              
      use_external_resource:
        default: false
      resource_id:
        default: ''
      mist_config:
        default: {}
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: mist.plugin.server.create
          inputs:
            args:
              default: {}
            mist_config:
              default: {}
        start:
          implementation: mist.plugin.server.start
          inputs:
            start_retry_interval:
              description: Polling interval until the server is active in seconds
              type: integer
              default: 30
            private_key_path:
              description: >
                Path to private key which matches the server's
                public key. Will be used to decrypt password in case
                the "use_password" property is set to "true"
              type: string
              default: ''
            mist_config:
              default: {}
        stop:
          implementation: mist.plugin.server.stop
          inputs:
            mist_config:
              default: {}
        delete:
          implementation: mist.plugin.server.delete
          inputs:
            mist_config:
              default: {}
      cloudify.interfaces.validation:
        creation:
          implementation: mist.plugin.server.creation_validation
          inputs:
            args:
              default: {}
            openstack_config:
              default: {}
        

  cloudify.mist.nodes.KeyPair:
    derived_from: cloudify.nodes.Root
    properties:
      use_external_resource:
        description: >
          Indicate whether the resource exists or if Cloudify should create the resource.
        type: boolean
        default: false
      resource_id:
        description: >
          Either the name or ID of the resource in Cloudify. If this is an existing
          resource, you should provide the name or the ID of the resource in Amazon AWS.
        type: string
        default: ''
      private_key_path:
        description: >
          The path where the key should be saved on the machine. If this is a bootstrap
          process, this refers to the local computer. If this will run on the manager,
          this will be saved on the manager.
        type: string
        default: ''
      mist_config:
        description: >
          A dictionary of values to pass to authenticate with the Mist API.
        default: {}
    interfaces:
      cloudify.interfaces.lifecycle:
        create: mist.plugin.keypair.create
        delete: mist.plugin.keypair.delete
      cloudify.interfaces.validation:
        creation: mist.plugin.keypair.creation_validation
